#!/usr/bin/env python3
"""The footer icons, one source for the mockup and for the firmware.

The marks used to be drawn at whatever size each shape wanted -- 11 rows
for the cloud, 19 for the shock burst -- and in a row they read as a set
of mismatched stickers. They share a height here instead: ICON_H is the
only size knob, each shape is described in units of it, and the widths
follow the shape, because a cloud squeezed into the same square as a
lightning bolt is either a blob or far too wide for the footer.

Everything is rasterised from a supersampled mask so the curves survive
at this size, and every definition carries the row count the code
actually produced. A header that disagrees with its own rows is not a
cosmetic error: on the panel it walks off the end of the array.

    python display-mock/icons.py            # preview strip + C definitions

render.py imports bitmaps() from here; the C definitions the firmware
compiles are generated by running this file.
"""
import math
from pathlib import Path
from PIL import Image, ImageDraw

ICON_H = 16      # every footer mark is this tall
SS = 16          # supersampling factor
SCALE = 10       # preview zoom


def threshold(big, w, h):
    """A pixel is ink when at least half of it is covered."""
    out = Image.new("1", (w, h), 0)
    op, bp = out.load(), big.load()
    for y in range(h):
        for x in range(w):
            n = sum(bp[x * SS + u, y * SS + v] for v in range(SS) for u in range(SS))
            op[x, y] = 1 if n * 2 >= SS * SS else 0
    return out


def canvas(w, h):
    big = Image.new("1", (w * SS, h * SS), 0)
    return big, ImageDraw.Draw(big), float(SS)


def disc(d, s, cx, cy, r, fill=1):
    d.ellipse([(cx - r) * s, (cy - r) * s, (cx + r) * s, (cy + r) * s], fill=fill)


# ---------------------------------------------------------------------
# Wi-Fi: three arcs over a dot. The fan is kept narrow enough that the
# widest arc does not push the icon past the shock burst beside it.
# ---------------------------------------------------------------------
WIFI_W = 20
WIFI_SPAN = 44.0          # degrees either side of straight up
WIFI_RADII = (5.4, 9.6, 13.8)
WIFI_THICK = 2.8
WIFI_DOT = 2.2


def wifi():
    """Three arcs over a dot, tested point by point.

    Building the arcs out of discs and then erasing the two half-planes
    outside the fan sounded simpler and ate the inner two arcs: the erase
    polygons are convex and the region to keep is not. Asking each sample
    whether its radius and its angle are both inside cannot go wrong that
    way.
    """
    w, h = WIFI_W, ICON_H
    cx, cy = w / 2.0, h - 0.5
    span = math.radians(WIFI_SPAN)
    half = WIFI_THICK / 2.0

    big = Image.new("1", (w * SS, h * SS), 0)
    bp = big.load()
    for py in range(h * SS):
        y = (py + 0.5) / SS
        for px in range(w * SS):
            x = (px + 0.5) / SS
            dx, dy = x - cx, cy - y          # dy up-positive
            if dy < 0:
                continue
            r = math.hypot(dx, dy)
            if r <= WIFI_DOT:                # the dot at the apex
                bp[px, py] = 1
                continue
            if abs(math.atan2(dx, dy)) > span:
                continue
            if any(abs(r - rr) <= half for rr in WIFI_RADII):
                bp[px, py] = 1
    return threshold(big, w, h)


# ---------------------------------------------------------------------
# Cloud: three overlapping discs on a flat base. Drawn taller and rounder
# than the old one rather than scaled up from it -- stretching the flat
# 19x11 shape to this height would have made it 28 px wide.
# ---------------------------------------------------------------------
CLOUD_W = 20


def cloud():
    w, h = CLOUD_W, ICON_H
    big, d, s = canvas(w, h)
    base = float(h)
    # The puffs have to reach the base themselves. Filling the gap with a
    # rectangle that starts above their centres squares off the outside
    # of the shape, and the first attempt came out as a mountain.
    disc(d, s, 10.2, 7.0, 5.4)          # dome
    disc(d, s, 4.6, 11.0, 4.6)          # left puff
    disc(d, s, 15.4, 10.8, 4.8)         # right puff
    d.rectangle([4.6 * s, 11.0 * s, 15.4 * s, base * s], fill=1)
    d.rectangle([0, base * s, w * s, h * s], fill=0)
    return threshold(big, w, h)


# ---------------------------------------------------------------------
# Map pin: a round head with a hole, over a tail whose flanks are the
# tangents from the tip to the head, so the outline stays continuous.
# ---------------------------------------------------------------------
PIN_W = 12
PIN_HOLE = 2.8


def pin():
    w, h = PIN_W, ICON_H
    r = w / 2.0
    cx = cy = r
    # A point that stops exactly on the last row covers less than half of
    # it and drops out, leaving the pin a row short of the others.
    tip = float(h) + 0.6
    big, d, s = canvas(w, h)
    disc(d, s, cx, cy, r, 1)
    cos_t = r / (tip - cy)
    sin_t = math.sqrt(1.0 - cos_t * cos_t)
    d.polygon([((cx - r * sin_t) * s, (cy + r * cos_t) * s),
               (cx * s, tip * s),
               ((cx + r * sin_t) * s, (cy + r * cos_t) * s)], fill=1)
    disc(d, s, cx, cy, PIN_HOLE, 0)
    return threshold(big, w, h)


# ---------------------------------------------------------------------
# Trip: a play triangle.
# ---------------------------------------------------------------------
TRIP_W = 9


def trip():
    w, h = TRIP_W, ICON_H
    big, d, s = canvas(w, h)
    d.polygon([(0, 0), (0, h * s), ((w - 0.5) * s, (h / 2.0) * s)], fill=1)
    return threshold(big, w, h)


# ---------------------------------------------------------------------
# Shock: a parcel with an impact burst off its top-right corner. The
# geometry is the one that was settled on at 19 rows, in units of that
# height, so changing ICON_H rescales it instead of redrawing it.
# ---------------------------------------------------------------------
SHOCK_REF_W, SHOCK_REF_H = 24.0, 19.0
SHOCK_BOX = (0.0, 7.0, 15.0, 18.0)
SHOCK_LID = 9.0
SHOCK_TAPE_X, SHOCK_TAPE_W = 6.0, 3.0
SHOCK_CX, SHOCK_CY = 16.8, 5.4
SHOCK_OUTER = [7.2, 7.0, 4.2, 3.0, 4.0, 6.8]   # up, up-right, ... up-left
SHOCK_INNER = 2.1
SHOCK_START = -90.0


def shock():
    k = ICON_H / SHOCK_REF_H
    w, h = int(round(SHOCK_REF_W * k)), ICON_H

    # The burst is a curve, so it goes through the supersampler; the box
    # is single-pixel rules, which would turn to mush if it did.
    big, d, s = canvas(w, h)
    pts = []
    n = len(SHOCK_OUTER)
    for i in range(n):
        ao = math.radians(SHOCK_START + 360.0 * i / n)
        ai = math.radians(SHOCK_START + 360.0 * (i + 0.5) / n)
        ro, ri = SHOCK_OUTER[i] * k, SHOCK_INNER * k
        pts.append(((SHOCK_CX * k + ro * math.cos(ao)) * s,
                    (SHOCK_CY * k + ro * math.sin(ao)) * s))
        pts.append(((SHOCK_CX * k + ri * math.cos(ai)) * s,
                    (SHOCK_CY * k + ri * math.sin(ai)) * s))
    d.polygon(pts, fill=1)
    star = threshold(big, w, h)

    box = Image.new("1", (w, h), 0)
    bd = ImageDraw.Draw(box)
    x0, y0, x1, y1 = [round(v * k) for v in SHOCK_BOX]
    lid = round(SHOCK_LID * k)
    tx, tw = round(SHOCK_TAPE_X * k), max(2, round(SHOCK_TAPE_W * k))
    bd.rectangle([x0, y0, x1, y1], outline=1)
    bd.line([(x0, lid), (x1, lid)], fill=1)
    bd.rectangle([tx, lid + 1, tx + tw - 1, lid + 2], fill=1)

    # One pixel of white around the burst, or the two shapes merge.
    sp, bp = star.load(), box.load()
    for y in range(h):
        for x in range(w):
            if not bp[x, y]:
                continue
            if any(0 <= x + dx < w and 0 <= y + dy < h and sp[x + dx, y + dy]
                   for dy in (-1, 0, 1) for dx in (-1, 0, 1)):
                bp[x, y] = 0

    out = Image.new("1", (w, h), 0)
    op = out.load()
    for y in range(h):
        for x in range(w):
            op[x, y] = 1 if (sp[x, y] or bp[x, y]) else 0

    # A pixel with no neighbour at all reads as dirt on the glass.
    # Diagonals count: spike tips attach corner to corner, and an
    # orthogonal-only test deletes every one of them.
    neigh = [(dx, dy) for dy in (-1, 0, 1) for dx in (-1, 0, 1) if dx or dy]
    for x, y in [(x, y) for y in range(h) for x in range(w) if op[x, y]
                 and not any(0 <= x + dx < w and 0 <= y + dy < h
                             and op[x + dx, y + dy] for dx, dy in neigh)]:
        op[x, y] = 0
    return out


# ---------------------------------------------------------------------
# Charge: a lightning bolt. Laid out in a box taller and wider than the
# icon wants to be and then cropped to its ink, because the extreme tips
# cover less than half a pixel and drop out.
# ---------------------------------------------------------------------
BOLT_BOX = (11.0, 18.0)       # in units of ICON_H = 16
BOLT = [(0.62, 0.00), (0.05, 0.57), (0.46, 0.57),
        (0.32, 1.00), (0.95, 0.43), (0.58, 0.43)]


def bolt():
    k = ICON_H / 16.0
    w, h = int(round(BOLT_BOX[0] * k)), int(round(BOLT_BOX[1] * k))
    big, d, s = canvas(w, h)
    d.polygon([(fx * w * s, fy * h * s) for fx, fy in BOLT], fill=1)
    out = threshold(big, w, h)
    return out.crop(out.getbbox())


# ---------------------------------------------------------------------
# Storage: two stacked drives. Plotted by hand rather than described as
# geometry -- it is all straight rules, and a rasteriser would only blur
# them. It was already on the common height.
# ---------------------------------------------------------------------
STORAGE = ("....#######....",
           "..##.......##..",
           ".#...........#.",
           "###############",
           "#.............#",
           "#.##...####...#",
           "#.##...####...#",
           "#.............#",
           "###############",
           ".#...........#.",
           "###############",
           "#.............#",
           "#.##...####...#",
           "#.##...####...#",
           "#.............#",
           "###############")


def storage():
    img = Image.new("1", (len(STORAGE[0]), len(STORAGE)), 0)
    px = img.load()
    for y, line in enumerate(STORAGE):
        for x, c in enumerate(line):
            px[x, y] = 1 if c == "#" else 0
    return img


# ---------------------------------------------------------------------
# Tap: a phone with the contactless arcs off its side -- the READY page's
# picture of "hold your phone to the box". Not a footer mark: it has its
# own height, and its own C type in the firmware (Pict, 48 rows max).
# ---------------------------------------------------------------------
TAP_H = 44
TAP_W = 42
TAP_PHONE = (2.0, 1.0, 23.0, 43.6)   # left, top, right, bottom
TAP_LINE = 2.4
TAP_ARC_C = (25.5, 15.0)            # arcs open to the right from here
TAP_ARC_R = (6.0, 10.5, 15.0)
TAP_ARC_SPAN = 42.0                 # degrees either side of horizontal


def tap():
    w, h = TAP_W, TAP_H
    big, d, s = canvas(w, h)
    l, t, r, b = TAP_PHONE
    rad = 3.2
    d.rounded_rectangle([l * s, t * s, r * s, b * s], radius=rad * s, fill=1)
    k = TAP_LINE
    d.rounded_rectangle([(l + k) * s, (t + k) * s, (r - k) * s, (b - k) * s],
                        radius=(rad - 1.2) * s, fill=0)
    # The earpiece and the button: a phone, not a door. A filled screen
    # was tried and read as a black slab at this size.
    d.rectangle([((l + r) / 2.0 - 3.0) * s, (t + k + 1.6) * s, ((l + r) / 2.0 + 3.0) * s,
                 (t + k + 3.0) * s], fill=1)
    disc(d, s, (l + r) / 2.0, b - k - 2.9, 1.6)
    # The arcs, tested point by point as for Wi-Fi.
    bp = big.load()
    cx, cy = TAP_ARC_C
    span = math.radians(TAP_ARC_SPAN)
    half = TAP_LINE / 2.0
    for py in range(h * SS):
        y = (py + 0.5) / SS
        for px in range(w * SS):
            x = (px + 0.5) / SS
            dx, dy = x - cx, y - cy
            if dx <= 0 or abs(math.atan2(dy, dx)) > span:
                continue
            rr = math.hypot(dx, dy)
            if any(abs(rr - a) <= half for a in TAP_ARC_R):
                bp[px, py] = 1
    return threshold(big, w, h)


def tap_rows():
    img = tap()
    w, h = img.size
    px = img.load()
    return tuple("".join("#" if px[x, y] else "." for x in range(w)) for y in range(h))


ICONS = [("WIFI", wifi), ("CLOUD", cloud), ("GNSS", pin), ("TRIP", trip),
         ("SHOCK", shock), ("CHARGE", bolt), ("STORAGE", storage)]


def bitmaps():
    """{name: tuple of '#'/'.' rows} -- what render.py blits."""
    out = {}
    for name, fn in ICONS:
        img = fn()
        w, h = img.size
        px = img.load()
        rows = tuple("".join("#" if px[x, y] else "." for x in range(w))
                     for y in range(h))
        assert len(rows) == h and all(len(r) == w for r in rows)
        out[name.lower()] = rows
    return out


def main():
    built = []
    for name, fn in ICONS:
        img = fn()
        w, h = img.size
        px = img.load()
        rows = ["".join("#" if px[x, y] else "." for x in range(w))
                for y in range(h)]
        assert len(rows) == h and all(len(r) == w for r in rows)
        built.append((name, w, h, rows, img))

    pad = 6
    total = sum(w + pad for _, w, _, _, _ in built) + pad
    strip = Image.new("L", (total, ICON_H + 2), 255)
    sd = ImageDraw.Draw(strip)
    x = pad
    for name, w, h, rows, img in built:
        ip = img.load()
        for yy in range(h):
            for xx in range(w):
                if ip[xx, yy]:
                    sd.point((x + xx, 1 + ICON_H - h + yy), fill=0)
        x += w + pad
    strip.resize((total * SCALE, (ICON_H + 2) * SCALE), Image.NEAREST).save(
        Path(__file__).parent / "out" / "footer_icons.png")

    for name, w, h, rows, _ in built:
        lead = " " * (len(f"static const Icon ICON_{name} = {{{w}, {h}, {{"))
        body = (",\n" + lead).join(f'"{r}"' for r in rows)
        print(f"static const Icon ICON_{name} = {{{w}, {h}, {{{body}}}}};")
        print()

    rows = tap_rows()
    lead = " " * len(f"static const Pict PICT_TAP = {{{TAP_W}, {TAP_H}, {{")
    body = (",\n" + lead).join(f'"{r}"' for r in rows)
    print(f"static const Pict PICT_TAP = {{{TAP_W}, {TAP_H}, {{{body}}}}};")


if __name__ == "__main__":
    main()
