#!/usr/bin/env python3
"""Convert IBM Plex subsets into Adafruit GFX fonts for the bench test.

The design in ../../display-mock is set in IBM Plex at sizes Adafruit's
bundled fonts do not reach (the hero numeral is 54px; FreeSans stops at
24pt). Glyphs are rasterised 1-bit with hinting, exactly as the mockup
renderer does, so what the panel shows matches the PNGs.

Only the characters each role needs are emitted, keeping the tables small.

    python tools/genfont.py > src/fonts_mcold.h
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

FONTS = Path(__file__).resolve().parents[3] / "mcold-spec" / "fonts"

# name, weight, pixel size, first char, last char
SUBSETS = [
    ("mColdHero80", "Bold", 80, "-", "9"),      # - . / 0-9
    ("mColdRead15", "Light", 15, " ", "Z"),     # min/max + charge-row values
    ("mColdCaps11", "SemiBold", 11, " ", "Z"),  # caps, digits, punctuation
    ("mColdUnit20", "Bold", 20, "C", "C"),      # the C of the unit only
    ("mColdTitle26", "Bold", 26, " ", "Z"),     # takeover headline
    ("mColdBody13", "Light", 13, " ", "z"),     # sentences, incl. lower case
    ("mColdStat13", "Medium", 13, " ", "Z"),    # charge state word
    ("mColdBig44", "Bold", 44, "%", "9"),       # state of charge
]


def render(font, ch):
    """Return (bits, w, h, xoff, yoff, xadv) for one glyph, 1-bit hinted."""
    pad, base = 40, 80
    img = Image.new("L", (pad * 3, base + 60), 0)
    d = ImageDraw.Draw(img)
    d.fontmode = "1"                      # monochrome with hinting, no AA
    d.text((pad, base), ch, font=font, fill=255, anchor="ls")
    xadv = round(d.textlength(ch, font=font))
    box = img.getbbox()
    if box is None:                       # blank glyph, e.g. space
        return [], 0, 0, 0, 0, xadv
    x0, y0, x1, y1 = box
    w, h = x1 - x0, y1 - y0
    px = img.load()
    bits = [1 if px[x0 + x, y0 + y] >= 128 else 0
            for y in range(h) for x in range(w)]
    return bits, w, h, x0 - pad, y0 - base, xadv


def pack(bits):
    """Adafruit packs glyphs as one continuous MSB-first bitstream."""
    out, acc, n = [], 0, 0
    for b in bits:
        acc = (acc << 1) | b
        n += 1
        if n == 8:
            out.append(acc)
            acc, n = 0, 0
    if n:
        out.append(acc << (8 - n))
    return out


def emit(name, weight, size, first, last):
    font = ImageFont.truetype(str(FONTS / f"IBMPlexSansThai-{weight}.ttf"),
                              size, layout_engine=ImageFont.Layout.BASIC)
    ascent, descent = font.getmetrics()
    bitmap, glyphs = [], []
    for code in range(ord(first), ord(last) + 1):
        bits, w, h, xo, yo, xadv = render(font, chr(code))
        glyphs.append((len(bitmap), w, h, xadv, xo, yo, chr(code)))
        bitmap.extend(pack(bits))

    print(f"// {name}: IBM Plex Sans Thai {weight} {size}px, "
          f"'{first}'..'{last}', {len(bitmap)} bytes")
    print(f"const uint8_t {name}Bitmaps[] PROGMEM = {{")
    for i in range(0, len(bitmap), 16):
        print("  " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",")
    print("};\n")

    print(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for off, w, h, xadv, xo, yo, ch in glyphs:
        label = "space" if ch == " " else ch
        print(f"  {{ {off:5d}, {w:3d}, {h:3d}, {xadv:3d}, {xo:4d}, {yo:4d} }},"
              f"   // '{label}'")
    print("};\n")

    print(f"const GFXfont {name} PROGMEM = {{")
    print(f"  (uint8_t *){name}Bitmaps,")
    print(f"  (GFXglyph *){name}Glyphs,")
    print(f"  0x{ord(first):02X}, 0x{ord(last):02X}, {ascent + descent} }};\n")


def main():
    print("// Generated by tools/genfont.py -- do not edit by hand.")
    print("// IBM Plex Sans Thai subsets matching ../../display-mock/render.py\n")
    print("#pragma once")
    print("#include <Adafruit_GFX.h>\n")
    for args in SUBSETS:
        emit(*args)


if __name__ == "__main__":
    main()
