#!/usr/bin/env python3
"""Adafruit-GFX fonts for the e-paper, from IBM Plex Sans Thai.

    python tools/genfont.py NAME WEIGHT SIZE FIRST LAST > src/fonts_NAME.h
    python tools/genfont.py mColdHead12 Bold 12 0x20 0x7A > src/fonts_head.h

Rendered the way display-mock/render.py renders (1-bit with hinting, no
antialiasing, BASIC layout so advances stay on whole pixels), so a glyph
on the panel matches the mockups pixel for pixel. Fonts come from
mcold-spec/fonts. Prints the header; nothing is written by itself.
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONTS = Path(__file__).resolve().parents[2] / "mcold-spec" / "fonts"


def main():
    name, weight, size, first, last = sys.argv[1:6]
    size, first, last = int(size), int(first, 0), int(last, 0)
    font = ImageFont.truetype(str(FONTS / f"IBMPlexSansThai-{weight}.ttf"), size,
                              layout_engine=ImageFont.Layout.BASIC)
    bits, glyphs = [], []
    ascent, descent = font.getmetrics()
    for code in range(first, last + 1):
        ch = chr(code)
        pad = size
        img = Image.new("1", (size * 3, size * 3), 0)
        d = ImageDraw.Draw(img)
        d.fontmode = "1"
        base = pad + ascent
        d.text((pad, base), ch, font=font, fill=1, anchor="ls")
        box = img.getbbox()
        adv = int(round(font.getlength(ch)))
        if not box:                       # space and friends
            glyphs.append((len(bits) // 8, 0, 0, adv, 0, 0, ch))
            continue
        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        start = len(bits)
        for y in range(y0, y1):
            for x in range(x0, x1):
                bits.append(1 if img.getpixel((x, y)) else 0)
        while len(bits) % 8:              # each glyph starts on a byte
            bits.append(0)
        glyphs.append((start // 8, w, h, adv, x0 - pad, y0 - base, ch))
    data = bytes(int("".join(map(str, bits[i:i + 8])), 2) for i in range(0, len(bits), 8))

    out = [f"// Generated by firmware/tools/genfont.py {name} {weight} {size} "
           f"{hex(first)} {hex(last)} -- do not edit by hand.",
           "// IBM Plex Sans Thai, 1-bit with hinting, as display-mock/render.py draws.",
           "#pragma once", '#include "gfxfont.h"', "",
           f"// {name}: IBM Plex Sans Thai {weight} {size}px, "
           f"'{chr(first)}'..'{chr(last)}', {len(data)} bytes",
           f"const uint8_t {name}Bitmaps[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        out.append("  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    out.append("};")
    out.append("")
    out.append(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for off, w, h, adv, xo, yo, ch in glyphs:
        label = "space" if ch == " " else ("backslash" if ch == "\\" else ch)
        out.append(f"  {{ {off:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:4d} }},   // '{label}'")
    out.append("};")
    out.append("")
    out.append(f"const GFXfont {name} PROGMEM = {{")
    out.append(f"  (uint8_t *){name}Bitmaps,")
    out.append(f"  (GFXglyph *){name}Glyphs,")
    out.append(f"  0x{first:02X}, 0x{last:02X}, {ascent + descent} }};")
    print("\n".join(out))


if __name__ == "__main__":
    main()
